### ISSUE TITLE
Why only listen to event? Why not a regular workflow?

### ISSUE THREAD

**Issue by hsblhsn** [superbrothers/close-pull-request#17]
I am using this action to check if a PR to `this` branch is allowed from `that` branch. It would be nice for me if it can be attached to regular workflow besides of `pull_request_target` event. So that I can cancel all other checks if the PR is closed or not allowed.

**Comment by superbrothers** [comment]
> I am using this action to check if a PR to this branch is allowed from that branch.

If a PR is not created from a fork, you should be able to use this action without any problem, since any other event can access the Secret. Please try it.

- https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
